hoshsadiq/adblock-nocoin-list

nocoin.txt
No need to block the 1st part contents.
=> Fix + Sort

nocoin.txt
Can we please modify the title of the list to make it more clear it's actually a filter list. 🙂
=> Modify List Title

hosts.txt
https://github.com/hoshsadiq/adblock-nocoin-list/pull/5
=> Modify Hosts file Title

nocoin.txt
Fix for https://github.com/hoshsadiq/adblock-nocoin-list/issues/8
=> Removed pr0gramm.com/api/

nocoin.txt
It's a "In-Browser XMR Miner", when look at the js file, it contains text from CoinHive.
=> In-Browser XMR Miner

README.md
=> upd readme.md

README.md
uBlock is actually a separate project from uBlock Origin (uBO).
=> Modify uBlock Project Name

README.md
Default included:
http://blogs.opera.com/desktop/2017/12/opera-50-beta-rc-cryptocurrency-mining-protection/
=> Add Opera browser to supported browsers.

nocoin.1blockpkg
Resolves issue #83 .
I also removed the items which are now included in 1Blocker's Tracker list.
>[Thousands of websites contain cryptocurrency mining scripts which significantly reduce battery life by executing code in background on your device.<br><br>Get the latest version of 1Blocker to ensure you are not affected: ...](https://twitter.com/1BlockerApp/status/930859279011254272)
> [To start blocking these cryptocurrency mining scripts update to the latest version from the App Store and enable the Block Trackers group.](https://twitter.com/1BlockerApp/status/930859384326049793)
=> updated for new items, removed duplicates from 1Blocker's tracker list

nocoin.txt
This is a fix for https://github.com/hoshsadiq/adblock-nocoin-list/issues/92
=> Added bablace.com

nocoin-ublock.txt, nocoin.txt
* Moved incompatible **Adblock Plus** [filters syntax](https://adblockplus.org/filters) in to a separate list.
* Integration of uBlock list (See "[!#include](https://github.com/MajkiIT/polish-ads-filter/issues/4898)" for details).
* http://i.imgur.com/H2InH1r.png
=> Splitted uBlock filters to a Sub-list

hosts.txt, nocoin.txt
- https\://sparechange.io/documentation/
- e.g http\://livenumetal.es/
=> Added "sparechange.io" (#106)

nocoin-ublock.txt
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt
=> Sync with "resource abuse" filter list

hosts.txt, nocoin.txt
https://github.com/hoshsadiq/adblock-nocoin-list/issues/131
=> Update & Changes

hosts.txt, nocoin.txt
`https://estream.to/ek8fhmt5ip57.html`
@ryanbr @okiehsch fyi.
=> Fix "estream.to"

hosts.txt, nocoin.txt
https://github.com/hoshsadiq/adblock-nocoin-list/pull/143
=> Update mining domains + Fix "kinokrad.co"

hosts.txt, nocoin-ublock.txt, nocoin.txt
https://forums.lanik.us/viewtopic.php?f=62&t=39991
=> Fix "adfreetv.ch"

nocoin.txt
For details ==> https://github.com/easylist/easylist/issues/916
=> Fix "webtorrent.io"

hosts.txt, nocoin-ublock.txt, nocoin.txt
* **NSFW** [hq-porns.com](https://github.com/uBlockOrigin/uAssets/issues/1559)
* `https://minr.pw/`
* https://pastebin.com/raw/ismmp6fv
=> Added minr.pw

nocoin-ublock.txt, nocoin.txt
* `https://gofile.io/?c=3t5Vk3`
=> Added "gofile.io"

hosts.txt, nocoin.txt
`https://akvideo.stream/9mchp4x9vcl7.html` / https://github.com/easylist/easylist/commit/31d7f09
`https://powvideo.net/embed-9ks9ofsu616y.html` / https://github.com/easylist/easylist/commit/41907ab
=> Update "akvideo.stream" & "powvideo.net"

nocoin.txt
https://github.com/hoshsadiq/adblock-nocoin-list/issues/137#issuecomment-366458325
=> Fix 137#issuecomment-366458325

hosts.txt, nocoin-ublock.txt, nocoin.txt
e.g `https://thevideo.me/5yedzglaf3kk`
=> Fix "thevideo.me"

hosts.txt, nocoin-ublock.txt, nocoin.txt
https://github.com/easylist/easylist/commit/115005fe78b4a66dfc72cab3297faa0d7f0718ba
https://github.com/easylist/easylist/commit/0ac7395dedeea7b2460017a91c5c11ea23ed39f7
=> Update / Sync with easyprivacy & uBo resource-abuse

hosts.txt, nocoin.txt
https://github.com/hoshsadiq/adblock-nocoin-list/issues/129#issuecomment-371971494
=> fix tomtop.com

hosts.txt, nocoin.txt
e.g. `http://ifrp.xyz/i5a8uzuw`
=> fix protect-iframe.com

hosts.txt, nocoin.txt
[uBlockOrigin/uAssets#1716](https://git.io/vxqOq)
=> added streambeam.io

nocoin.txt
* Update general blocking
* fix https://forums.lanik.us/viewtopic.php?f=64&t=40259 (@ryanbr fyi)
=> Update general blocking

hosts.txt, nocoin-ublock.txt, nocoin.txt
fix 
* centrum-dramy.pl
* hentai-online.pl (**nsfw**)
https://github.com/uBlockOrigin/uAssets/commit/00a45c01
=> Update + Sync with uBo resource-abuse

hosts.txt, nocoin-ublock.txt, nocoin.txt
For details see https://github.com/hoshsadiq/adblock-nocoin-list/pull/206
=> Fix deltabit.co

hosts.txt, nocoin-ublock.txt, nocoin.txt
https://forums.lanik.us/viewtopic.php?f=62&t=40553
=> fix biter.tv & byter.tv

hosts.txt, nocoin.txt
e.g. `http://www.milujivareni.cz/`
@ryanbr  @okiehsch fyi.
=> add webminerpool.com

hosts.txt, nocoin.txt
```
http://baltak.biz/court1.php
http://baltak.biz/blok.php?id=http://www.lshstreams.com/embed.php?u=court1&vw=700&vh=480&live.realstreamunited.com=baltak.com
```
=> fix baltak.biz (https://forums.lanik.us/viewtopic.php?p=137426#p137426)

hosts.txt, nocoin-ublock.txt, nocoin.txt
=> M: Moved CSP filter to the main list + Fix mining on some websites

hosts.txt, nocoin.txt
https://forums.lanik.us/viewtopic.php?f=62&t=41585
=> Update coinimp.com domains

nocoin.txt
Ss 
* https://vgy.me/KmsRXj.png
* https://vgy.me/Qw5stz.png
=> fix instant.io

nocoin.txt
It appears that a few `$` options anchors are missing.
=> Add missing options anchors

hosts.txt, nocoin.txt
Subdomains have been suspended after being reported to fraud@netlify.com
=> Removed netlify.com

nocoin.txt
See https://github.com/hoshsadiq/adblock-nocoin-list/issues/351
=> Add another subdomain required for Klipse

nocoin.txt
In the frame `https://gogo-play.net/embed.php?id=NDA3OTI=&title=.Hack%2F%2FG.U.+Returner+episode+1&typesub=&pl=jw8` there is a player **Server Hyrax**, the rule in your sheet blocks websocket `theresamackenzie.xyz` from this player and the video does not play, the error **Error loading media: Unknown network error** appears.
=> fix redirect-ads.com

nocoin-ublock.txt
See: https://github.com/gorhill/uBlock/wiki/Resources-Library
=> Update uBO scriptlet syntax
